[package]
name = "zippopotamus"
version = "0.0.3"
edition = "2021"

[profile.release]
opt-level = 2

[dependencies]
bincode = "1.3.3"
bitvec = "1.0.1"
caffeine = "0.2.0"
priority-queue = "2.3.1"
serde = { version = "1.0.219", features = ["derive"] }

webbrowser = "1.0.4"
